server:
  port: 8200
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost     # eureka服务端的实力名称
  client:
    fetch-registry: true  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: true   # false表示自己不需要向注册中心注册自己
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:8300/eureka/,http://localhost:8100/eureka/
  server:
    #开启自我保护机制
    enable-self-preservation: true





